var a = 10;
document.writeln("<h1>Result</h1 > ");
document.writeln("<p>the value of a is : " + a + "</p> ");
document.writeln("<hr/> ");
document.writeln("<br/> ");
document.writeln("<p>the value of ++a is : " + ++a + "</p> ");
document.writeln("<p>Now the value of a is : " + a + "</p> ");
document.writeln("<br/> ");
document.writeln("<p>the value of a++ is : " + a++ + "</p> ");
document.writeln("<p>Now the value of a is : " + a + "</p> ");
document.writeln("<br/> ");
document.writeln("<p>the value of --a is : " + --a + "</p> ");
document.writeln("<p>Now the value of a is : " + a + "</p> ");
document.writeln("<br/> ");
document.writeln("<p>the value of a is : " + a-- + "</p> ");
document.writeln("<p>Now the value of a is : " + a + "</p> ");